### ISSUE TITLE
Match  artists name

### ISSUE THREAD

**Issue by kumar245** [popurichaitany/Movies_Match#5]

**Comment by williamgdev** [comment]
Use the Oracle of Bacon Api
following this example
http://oracleofbacon.org/cgi-bin/json?p=38b99ce9ec87&a=Kevin%20Bacon&b=Eminem

If you have an error with the artist name, please look at the xml file suggest you all names that you can use.
http://oracleofbacon.org/cgi-bin/json?p=38b99ce9ec87&a=Kevin%20Bacon&b=Eminen

**Comment by williamgdev** [comment]
Here is the API details. 
https://github.com/saasbook/hw-oracle-of-bacon/blob/master/README.md
